PROPER_DIRECTION_PROBABILITY = 50

LENGTH_WEIGHT = 2
SEGMENTS_WEIGHT = 1
CROSS_WEIGHT = 50
PATH_OUT_OF_BOARD = 100
LENGTH_OUT_OF_BOARD = 50

TOURNAMENT_N = 5

CROSSING_PROBABILITY = 50
GENE_CHANGE_PROBABILITY = 50

MUTATION_PROBABILITY = 70

