PROPER_DIRECTION_PROBABILITY = 50

LENGTH_WEIGHT = 5
SEGMENTS_WEIGHT = 1
CROSS_WEIGHT = 100
PATH_OUT_OF_BOARD = 200
LENGTH_OUT_OF_BOARD = 100

TOURNAMENT_N = 0.1

CROSSING_PROBABILITY = 50
GENE_CHANGE_PROBABILITY = 50

MUTATION_PROBABILITY = 80

